vich_uploader:
    db_driver: orm

    metadate:
        type: attribute

    mappings:
       videos:
           uri_prefix: /videos
           upload_destination: '%kernel.project_dir%/data/videos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
